fix "ImportError: cannot import name 'StrEnum' from 'enum'"
The StrEnum class was introduced in Python 3.11. StrEnum does not exist in the Python 3.10 environment.